name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

defaults:
  run:
    working-directory: ./aplicacao

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build App
        run: docker-compose up --build -d

  docker-test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Reset db
        run: docker-compose run app rails db:reset

      - name: Docker Test
        run: docker-compose run app rspec

  run-lint:
    name: Run Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Lint
        run: docker-compose run app bash -c "gem install rubocop; rubocop -A --fail-level F"
